# Generated by Django 5.1 on 2025-11-30 07:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='uuid', primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='建立日期', verbose_name='建立日期')),
                ('create_user', models.CharField(help_text='建立者', max_length=50, verbose_name='建立者')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='修改日期', verbose_name='修改日期')),
                ('last_modified_user', models.CharField(help_text='修改者', max_length=50, verbose_name='修改者')),
                ('dept_code', models.CharField(help_text='科室代碼', max_length=50, verbose_name='科室代碼')),
                ('dept_name', models.CharField(help_text='科室名稱', max_length=100, verbose_name='科室名稱')),
                ('dept_group', models.CharField(blank=True, help_text='部門名稱', max_length=100, null=True, verbose_name='部門名稱')),
            ],
            options={
                'verbose_name': '科室檔',
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='uuid', primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='建立日期', verbose_name='建立日期')),
                ('create_user', models.CharField(help_text='建立者', max_length=50, verbose_name='建立者')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='修改日期', verbose_name='修改日期')),
                ('last_modified_user', models.CharField(help_text='修改者', max_length=50, verbose_name='修改者')),
                ('menu_1st', models.CharField(help_text='主選單名稱', max_length=128, verbose_name='主選單名稱')),
                ('menu_1st_icon', models.CharField(help_text='主選單icon', max_length=128, verbose_name='主選單icon')),
                ('menu_1st_sort', models.SmallIntegerField(blank=True, help_text='主選單排序', null=True, verbose_name='主選單排序')),
                ('menu_2st', models.CharField(blank=True, help_text='次選單名稱', max_length=128, null=True, verbose_name='次選單名稱')),
                ('menu_2st_url', models.CharField(blank=True, help_text='選單url', max_length=128, null=True, verbose_name='選單url')),
                ('menu_2st_sort', models.SmallIntegerField(blank=True, help_text='次選單排序', null=True, verbose_name='次選單排序')),
                ('report_url', models.CharField(blank=True, help_text='Power BI報表url', max_length=300, null=True, verbose_name='Power BI報表url')),
            ],
            options={
                'verbose_name': '選單檔',
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='menugroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='uuid', primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='建立日期', verbose_name='建立日期')),
                ('create_user', models.CharField(help_text='建立者', max_length=50, verbose_name='建立者')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='修改日期', verbose_name='修改日期')),
                ('last_modified_user', models.CharField(help_text='修改者', max_length=50, verbose_name='修改者')),
                ('menu_group', models.CharField(help_text='群組名稱', max_length=128, verbose_name='群組名稱')),
                ('menu_id', models.JSONField(blank=True, help_text='群組代碼', null=True, verbose_name='群組代碼')),
            ],
            options={
                'verbose_name': '選單群組檔',
                'db_table': 'menugroup',
            },
        ),
        migrations.CreateModel(
            name='parameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='uuid', primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='建立日期', verbose_name='建立日期')),
                ('create_user', models.CharField(help_text='建立者', max_length=50, verbose_name='建立者')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='修改日期', verbose_name='修改日期')),
                ('last_modified_user', models.CharField(help_text='修改者', max_length=50, verbose_name='修改者')),
                ('pa_type', models.CharField(blank=True, help_text='參數類別', max_length=50, null=True, verbose_name='參數類別')),
                ('pa_key', models.CharField(help_text='參數名稱', max_length=50, verbose_name='參數名稱')),
                ('pa_value', models.CharField(help_text='參數值', max_length=500, verbose_name='參數值')),
                ('pa_sort', models.SmallIntegerField(help_text='排序', null=True, verbose_name='排序')),
                ('pa_comment', models.CharField(blank=True, help_text='備註', max_length=100, null=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '參數檔',
                'db_table': 'parameter',
            },
        ),
    ]
