# Generated by Django 5.1 on 2025-11-30 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manages', to=settings.AUTH_USER_MODEL)),
                ('subordinate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用者上下關係',
                'db_table': 'userrelation',
            },
        ),
        migrations.CreateModel(
            name='userstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lock', models.BooleanField(default=False, help_text='帳號是否鎖定', verbose_name='帳號是否鎖定')),
                ('lock_date', models.DateTimeField(help_text='銷定時間', null=True, verbose_name='銷定時間')),
                ('is_resetpwd', models.BooleanField(default=False, help_text='密碼是否需要重設', verbose_name='密碼是否需要重設')),
                ('loginfail_times', models.SmallIntegerField(default=0, help_text='密碼是否需要重設', verbose_name='密碼是否需要重設')),
                ('password1', models.CharField(blank=True, help_text='前一次密碼', max_length=128, null=True, verbose_name='前一次密碼')),
                ('password2', models.CharField(blank=True, help_text='前二次密碼', max_length=128, null=True, verbose_name='前二次密碼')),
                ('password3', models.CharField(blank=True, help_text='前三次密碼', max_length=128, null=True, verbose_name='前三次密碼')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commons.department')),
                ('menugroup', models.ForeignKey(blank=True, help_text='選單群組', null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.menugroup', verbose_name='選單群組')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '使用者狀態',
                'db_table': 'userstatus',
            },
        ),
    ]
